### ISSUE TITLE
What does 'doe' mean?

### ISSUE THREAD

**Issue by ZooeyMiller** [facn2/Book-Share-RM#32]
Probably just me, but what does 'doe' mean? 

![workspace 1_019](https://user-images.githubusercontent.com/21139983/29158482-dda177b2-7db3-11e7-97aa-edd418594f31.png)

**Comment by veredrec** [comment]
From looking at the code this is for "last name", and this is the placeholder. But the "first name" input (which has a placeholder of "John") is commented out, why?

**Comment by ZooeyMiller** [comment]
Looking much better!
