### ISSUE TITLE
pg and http are required but not used in handlers.js

### ISSUE THREAD

**Issue by RQ16** [facn2/Book-Share-RM#34]
https://github.com/facn2/Book-Share-RM/blob/95f5d69b6dc03e72dc0e6542072c06b408b4a979/src/handlers.js#L3
https://github.com/facn2/Book-Share-RM/blob/95f5d69b6dc03e72dc0e6542072c06b408b4a979/src/handlers.js#L4

**Comment by RQ16** [comment]
In router.js as well!
https://github.com/facn2/Book-Share-RM/blob/95f5d69b6dc03e72dc0e6542072c06b408b4a979/src/router.js#L3-L4

**Comment by matthewdking** [comment]
@RQ16 we removed these! good spot :eyes:

**Comment by RQ16** [comment]
Looks :+1:!
