### ISSUE TITLE
Section is in head element

### ISSUE THREAD

**Issue by RQ16** [facn2/Book-Share-RM#36]
https://github.com/facn2/Book-Share-RM/blob/95f5d69b6dc03e72dc0e6542072c06b408b4a979/public/index.html#L12-L16
It should be moved to the body element. Head is only for metadata!

**Comment by KatiaAsh** [comment]
We have moved section to head element
@RQ16  Please have a look and close the issue

**Comment by RQ16** [comment]
:+1:
