### ISSUE TITLE
CSS indentation

### ISSUE THREAD

**Issue by RQ16** [facn2/Book-Share-RM#39]
https://github.com/facn2/Book-Share-RM/blob/95f5d69b6dc03e72dc0e6542072c06b408b4a979/public/style.css#L107-L114
https://github.com/facn2/Book-Share-RM/blob/95f5d69b6dc03e72dc0e6542072c06b408b4a979/public/style.css#L118-L119
Fix yo indentation, please!

**Comment by Karyum** [comment]
also in the back end 
https://github.com/facn2/Book-Share-RM/blob/master/src/queries/getData.js
was it something that you guys agreed upon to use 4 space indentation?

**Comment by KatiaAsh** [comment]
We have deleted the indentation
@Karyum Please have a look 
@RQ16  Please have a look and close the issue

**Comment by Karyum** [comment]
Have you also fixed this in the backend @KatiaAsh ??

**Comment by KatiaAsh** [comment]
@Karyum it only shows with spaces in GitHub when you open the atom you won't find this spaces

**Comment by RQ16** [comment]
Reopened because I created the issue

**Comment by RQ16** [comment]
@Karyum Why close the issue? It is still not fixed and you did not open it.
@KatiaAsh I did clone it, yet found that it was still not indented. In addition, found more lines that need to be fixed:
https://github.com/facn2/Book-Share-RM/blob/95f5d69b6dc03e72dc0e6542072c06b408b4a979/public/style.css#L101-L104

**Comment by Karyum** [comment]
@RQ16 sorry about that my mistake :maple_leaf:
