### ISSUE TITLE
router is doing handling

### ISSUE THREAD

**Issue by m4v15** [facn2/Book-Share-RM#54]
See [this](https://github.com/facn2/facnrecipe/issues/40) from @JWLD.

https://github.com/facn2/Book-Share-RM/blob/master/src/router.js#L16-L26

and

https://github.com/facn2/Book-Share-RM/blob/master/src/router.js#L28-L49

should both be seperate handler functions

**Comment by ghost** [comment]
sorted . good point big man

**Comment by m4v15** [comment]
NIIIICE! (although for consistency, and as standard, next time always send `(request, response)` in that order)
